name: Publish Enclave CC CI payloads for Confidential Containers
on:
  push:
    branch:
      - main

jobs:
  build-asset:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        asset:
          - HW
          - SIM
    steps:
      - name: Login to quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.COCO_QUAY_DEPLOYER_USERNAME }}
          password: ${{ secrets.COCO_QUAY_DEPLOYER_PASSWORD }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # This is needed in order to keep the commit ids history
      - name: Build Enclave CC Payload using SGX_MODE=${{ matrix.asset }}
        run: |
          ./tools/packaging/build/build_payload.sh 
        env:
          SGX_MODE: ${{ matrix.asset }}
          CI: yes
          PUSH: yes
